# site settings

title: cvless
description: Jekyll theme for a beautiful online CV
taglong: Jekyll theme for a beautiful online CV
tagshort: Jekyll theme
url: https://gaeduck-portfolio.netlify.app
baseurl: ""
permalink: pretty
repo: https://github.com/Gaeduck-0908/Gaeduck_PortFolio_Site

# author settings

author:
  name: Gaeduck
  email: gms8757@naver.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  facebook: username
  github: Gaeduck-0908
  instagram: kimtaehan-0908
  linkedin: username
  stackoverflow: 0000000/username
  twitter: username

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
